### ISSUE TITLE
cannot import name 'gcd' from 'fractions'

### ISSUE THREAD

**Issue by Rubery** [pretrehr/Sports-betting#4] opened 2020-11-12 19:14 UTC
C:\Users\x\Desktop\Sports-betting-master>python interface_pysimplegui.py
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Sports-betting-master\interface_pysimplegui.py", line 20, in <module>
    from sportsbetting.auxiliary_functions import get_nb_issues
  File "C:\Users\x\Desktop\Sports-betting-master\sportsbetting\auxiliary_functions.py", line 14, in <module>
    import baseconvert
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\baseconvert\__init__.py", line 1, in <module>
    from baseconvert.baseconvert import BaseConverter
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\baseconvert\baseconvert.py", line 118, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (C:\Users\x\AppData\Local\Programs\Python\Python39\lib\fractions.py)

**Comment by pretrehr** [comment] 2020-11-12 20:29
Hi Rubery,
Thanks for your message.
One of the imported packages was not compatible with Python 3.9. The problem should be fixed now. Can you do a ```git pull``` and tell me if the problem is solved ?
Thanks
pretrehr

**Comment by Rubery** [comment] 2020-11-12 20:41
yes, works now. Thank you

**Closed** 2020-11-12 20:45 UTC
